### ISSUE TITLE
Please tag and version this project

### ISSUE THREAD

**Issue by jredville** [lsegal/gucumber#19]
Tags and versions aid in packaging for things like .deb files, and for anyone wanting to use Glide and other version based package managers to version their dependencies. It would also help ensure that if you make a breaking change, we don't pull it down until we are ready.

**Comment by lsegal** [comment]
@jredville second thing first: if this project were versioned, it would definitely be a 0.x.y semver, which wouldn't guarantee backward compatibility across releases, so versioning doesn't really solve that problem for you.

I'm not opposed to adding versions to projects in general, but keep in mind that this project is small, relatively young, and not heavily maintained, so a lot of things do just go into master without triggering a release. There's added overhead in planning a release and tag schedule for batches of changes, and frankly, that probably wouldn't get done reliably (I use the web UI to merge patches, for example). The alternative would just be a script to tag every single commit as a separate semver tag just to make things like Glide work, but that seems equally ugly. That's what SHAs are for.

You're better off just treating every commit like a new release until this project becomes more mature. Presumably Glide can use SHAs as versions in some way?

**Comment by jredville** [comment]
@lsegal understood. Glide can use SHAs just fine, and I can do that for gucumber. I'm happy to hear that this would go semver in the future when it is more stable, and appreciate the thoughtful reply
