### ISSUE TITLE
gucumber running on Windows

### ISSUE THREAD

**Issue by XavierVal** [lsegal/gucumber#4]
Hello, I was trying to execute the gucumber on windows but it doesn't look that it's ready for it. Look what it shows when I try a launch "go test" :

```
C:\Go\bin\src\github.com\lsegal>go test
C:\Users\x\AppData\Local\Temp\go-build605331559\github.com\lsegal\_test\lsegal.test.exe flag redefined: tags
panic: C:\Users\x\AppData\Local\Temp\go-build605331559\github.com\lsegal\_test\lsegal.test.exe flag redefined: tags

goroutine 1 [running]:
flag.(*FlagSet).Var(0xc0820441e0, 0x1824d0, 0x935fc0, 0x78f790, 0x4, 0x7fbb70, 0x33)
        c:/go/src/flag/flag.go:679 +0x49b
flag.Var(0x1824d0, 0x935fc0, 0x78f790, 0x4, 0x7fbb70, 0x33)
        c:/go/src/flag/flag.go:694 +0x6d
github.com/lsegal.init┬À1()
        C:/Go/bin/src/github.com/lsegal/run_main.go:22 +0x84
github.com/lsegal.init()
        C:/Go/bin/src/github.com/lsegal/stepdef.go:207 +0x316
main.init()
        github.com/lsegal/_test/_testmain.go:60 +0x56
exit status 2
FAIL    github.com/lsegal       0.415s
```

This is due to the this line https://github.com/lsegal/gucumber/blob/master/gherkin/parser.go#L10 
(that is used in https://github.com/lsegal/gucumber/blob/master/runner.go#L89) 

```
	lines := strings.Split(data, "\n")
```

For instance you could use the bufio's scanner to accumulate every .Text() in a []string to pass it to gherkin/parser.go- gherkin.ParseFilename

Source: http://stackoverflow.com/questions/8757389/reading-file-line-by-line-in-go

BTW. Thank you for this cucumber approach in Go!

**Comment by XavierVal** [comment]
The real error log due to the windows line break format was this one:

```
C:\Go\bin\src\github.com\lsegal\gucumber>gucumber
panic: parse error (scenario.feature:4): expected "Feature:", found "\r".

goroutine 1 [running]:
github.com/lsegal/gucumber.(*Context).RunDir(0x8f0ae0, 0x770db0, 0x8, 0x439773, 0x0, 0x0)
        C:/Go/bin/src/github.com/lsegal/gucumber/runner.go:57 +0x390
main.main()
        C:/Go/bin/src/github.com/lsegal/gucumber/features/_test/gucumbertest__.go:17 +0x47
exit status 2
panic: exit status 1

goroutine 1 [running]:
github.com/lsegal/gucumber.RunMain()
        C:/Go/bin/src/github.com/lsegal/gucumber/run_main.go:40 +0x291
main.main()
        C:/Go/bin/src/github.com/lsegal/cmd/gucumber/gucumber.go:6 +0x22
```

**Comment by lsegal** [comment]
Thanks for reporting this. Let me know if you're still having this issue and I can take a look. If you want to submit a PR I'd take it.

**Comment by zyzjaffery** [comment]
I had a fresh checkout and tried running your basic scenario in Windows cmd, and had the same issue as @XavierVal. I also tried to run it via Git Bash in Windows, got different error as below:

panic: could not determine package path for internal\features\basic\step_definitions.go

goroutine 1 [running]:
github.com/lsegal/gucumber.RunMain()
        C:/.../goprojects/src/github.com/lsegal/gucumber/run_main.go:40 +0x291
main.main()
        C:/.../goprojects/src/github.com/lsegal/gucumber/cmd/gucumber/gucumber.go:6 +0x22

We are looking for a BDD tool for our project written in GO. Your project seems a perfect fit for it, but we are stuck by evaluating it in Windows:(

**Comment by lsegal** [comment]
@zyzjaffery as a reasonable workaround you can save your .feature files with UNIX line endings rather than Windows line endings (remove the `\r`s) and gucumber should be able to parse them. That said, seems like an easy fix to get Windows line endings working-- I can take a look at this or someone can build a PR to use something like [scanner](http://golang.org/pkg/text/scanner/).

**Comment by lsegal** [comment]
Should be fixed now, thanks for reporting.

**Comment by sqavenky** [comment]
I am getting the same error on Windows7. Please let me know what was the fix. I pulled the latest from github.

panic: could not determine package path for internal\features\basic\step_definitions.go

goroutine 1 [running]:
github.com/lsegal/gucumber.RunMain()
C:/.../goprojects/src/github.com/lsegal/gucumber/run_main.go:40 +0x291
main.main()
C:/.../goprojects/src/github.com/lsegal/gucumber/cmd/gucumber/gucumber.go:6 +0x22

**Comment by lsegal** [comment]
@sqavenky you can confirm that this is a newline issue by converting your steps file to use UNIX newlines.

**Comment by sqavenky** [comment]
I believe it is the same issue. Same code runs fine on my Mac OS X. But not on Windows7. I have go 1.6.2 version.

**Comment by lsegal** [comment]
@sqavenky have you confirmed this by replacing newlines?
